language: cpp
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential
    cmake gettext git-core gpsd gpsd-clients libgps-dev wx-common libwxgtk3.0-dev libglu1-mesa-dev
    libgtk2.0-dev wx3.0-headers libbz2-dev libtinyxml-dev libportaudio2 portaudio19-dev
    libcurl4-openssl-dev libexpat1-dev libcairo2-dev libarchive-dev liblzma-dev libexif-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo libexif xz libarchive;
    wget http://opencpn.navnux.org/build_deps/wx312_opencpn50_macos109.tar.xz; tar xJf
    wx312_opencpn50_macos109.tar.xz -C /tmp; export PATH="/usr/local/opt/gettext/bin:$PATH";
    echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile; wget http://s.sudre.free.fr/Software/files/Packages.dmg;
    hdiutil attach Packages.dmg; sudo installer -pkg "/Volumes/Packages 1.2.5/Install Packages.pkg" -target "/";
    fi
script:
  - mkdir -p build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DwxWidgets_CONFIG_EXECUTABLE=/tmp/wx312_opencpn50_macos109/bin/wx-config
    -DwxWidgets_CONFIG_OPTIONS="--prefix=/tmp/wx312_opencpn50_macos109" -DCMAKE_INSTALL_PREFIX=/tmp/opencpn
    -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; fi
  - make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make create-pkg; ls -la; pwd; fi
env:
  global:
    - secure: dXjA+mZQ3uxcLXLdtjRUMjbJ3otOboFL/jyckTPi9wjvPSOiQQ1OxVMGIoxUCRU9F1c/f6lk1cKtEfXBwEqHTxADRYY/FkyWPPQO4aRWSmZpU0wN19NBCKkVygeSTCYmM5bNrvgsKyG4x7OqvJBvAorU+T8XezHni69UcJQI0rw=
addons:
  coverity_scan:
    project:
      name: nohal/ocpndebugger_pi
      description: Build submitted via Travis CI
    notification_email: pavel@kalian.cz
    build_command_prepend: mkdir -p build; cd build; cmake ..; make clean
    build_command: make
    branch_pattern: coverity_scan
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export RELEASE_PKG_FILE=$(ls *.pkg); fi
deploy:
  - provider: releases
    api_key:
      secure: qnlIiYkqf8+zluKup/skVFO3aKWr94QrNSJc1e4kTnLbDfy1STpdSZRxn3qriZEE9mbqA34QXAM2KCxQkhe5BEaOM5adGTtmLRn8ha6FQylrDTUNMxvvZH4IMAsP0abQEq5pnp0fd3ZPkGaU5FspKocgdo+DdqdGEa7zxceZsYw=
    file: "${RELEASE_PKG_FILE}"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_OS_NAME = osx"
      repo: nohal/ocpndebugger_pi
  - provider: launchpad
    slug: "~nohal/ocpndebugger-pi/+git/master"
    oauth_token:
      secure: XnkZHbxALvy4uQrL6/RmN+8/b1h8HwV6wi3h+iuPT815OQA7EIrHx06o112cNI2QuBiODVneyWCxr/OCGjwlkwNRyEIwc7Q5uBHYGJB6QqMJYEBEsMkTkZ/Pe+TaaE+S1TQJ5s1GgTTTuZxQYZfGU+SjLu7fTzsZ71nsuEpPxnU=
    oauth_token_secret:
      secure: sctt53xLZUg7aotrfOgUwQ11jzGXyQzOeFyi3az90JLF/3c2TBecauTPFwq1Qdtidbkw22Bm3Wk3Vv3PjL0BGfRdnhQZT8HiR7PPcflqaVSn3ws+LYgA0Yue5Z7NzTct0FKNItewtj+p4Vo5Sxmx6a4dp/5RHapAgmHW9gk/hk8=
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_OS_NAME = linux"
      repo: nohal/ocpndebugger_pi
