language: cpp
compiler:
  - gcc

#branches:
#  only:
#    - master

before_install:
  - sudo apt-get update
install:
  - sudo apt-get install build-essential cmake gettext git-core gpsd gpsd-clients libgps-dev wx-common libwxgtk3.0-dev libglu1-mesa-dev libgtk2.0-dev wx3.0-headers libbz2-dev libtinyxml-dev libportaudio2 portaudio19-dev libcurl4-openssl-dev libexpat1-dev libcairo2-dev
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TM0wWPKq1QoV5IsY+LLVvA6T04EOhduyO8d+7k+qkLb+PRG9Pjs01bzwsiQQs2Bk08KsnZkSdgAzMTv+EETH+1ptHjW0QGBHO1EfYUw9ZkLaJl+HRiTkVozUAfltTlrOeUgsWNX4e59Id8iMB00htOSmBim4CgcaFaSfmRGCto0="

#addons:
#  coverity_scan:
#    project:
#      name: "nohal/ocpndebugger_pi"
#      description: "Build submitted via Travis CI"
#    notification_email: pavel@kalian.cz
#    build_command_prepend: "mkdir -p build; cd build; cmake .."
#    build_command:   "make -j 4"
#    branch_pattern: coverity_scan
#    build_script_url: "https://raw.githubusercontent.com/nohal/objsearch_pi/master/scan_script.sh"
