/* Autogenerated by png2wx.pl on Thu Jun  7 12:35:24 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_ocpndebugger;
extern wxBitmap *_img_ocpndebugger_pi;

#endif /* ICONS_H */
